comment "Exported from Arsenal by Maj W. Jones";
 
comment "Remove existing items";
removeAllWeapons _this;
removeAllItems _this;
removeAllAssignedItems _this;
removeUniform _this;
removeVest _this;
removeBackpack _this;
removeHeadgear _this;
removeGoggles _this;
 
comment "Add containers";
_this forceAddUniform "rhs_uniform_FROG01_wd";
for "_i" from 1 to 7 do {_this addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 6 do {_this addItemToUniform "ACE_morphine";};
for "_i" from 1 to 2 do {_this addItemToUniform "ACE_tourniquet";};
_this addItemToUniform "ACE_EarPlugs";
_this addItemToUniform "ACE_epinephrine";
for "_i" from 1 to 3 do {_this addItemToUniform "ACE_quikclot";};
_this addItemToUniform "rhsusf_ANPVS_15";
_this addVest "lbt_comms_coy";
for "_i" from 1 to 6 do {_this addItemToVest "ACE_fieldDressing";};
for "_i" from 1 to 2 do {_this addItemToVest "ACE_morphine";};
_this addItemToVest "ACE_tourniquet";
_this addItemToVest "rhs_mag_mk3a2";
_this addItemToVest "rhs_mag_an_m8hc";
for "_i" from 1 to 5 do {_this addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag";};
_this addItemToVest "30Rnd_556x45_Stanag";
for "_i" from 1 to 2 do {_this addItemToVest "9Rnd_45ACP_Mag";};
_this addBackpack "tfw_ilbe_blade_gr";
_this addItemToBackpack "ACE_surgicalKit";
for "_i" from 1 to 11 do {_this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 10 do {_this addItemToBackpack "ACE_elasticBandage";};
for "_i" from 1 to 7 do {_this addItemToBackpack "ACE_quikclot";};
_this addItemToBackpack "tfw_rf3080Item";
_this addItemToBackpack "tfw_whip";
_this addItemToBackpack "tfw_dd";
_this addItemToBackpack "ACE_EarPlugs";
for "_i" from 1 to 10 do {_this addItemToBackpack "ACE_packingBandage";};
for "_i" from 1 to 2 do {_this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 2 do {_this addItemToBackpack "rhs_mag_mk84";};
for "_i" from 1 to 2 do {_this addItemToBackpack "rhs_mag_m18_red";};
for "_i" from 1 to 2 do {_this addItemToBackpack "rhs_mag_m18_green";};
for "_i" from 1 to 2 do {_this addItemToBackpack "rhs_mag_m18_purple";};
_this addItemToBackpack "rhs_mag_m18_yellow";
_this addItemToBackpack "rhs_mag_mk3a2";
_this addHeadgear "rhsusf_mich_bare_norotos_alt_headset";
_this addGoggles "rhs_googles_clear";
 
comment "Add weapons";
_this addWeapon "rhs_weap_m4a1_carryhandle_mstock_grip3";
_this addPrimaryWeaponItem "rhsusf_acc_SF3P556";
_this addPrimaryWeaponItem "rhsusf_acc_anpeq15";
_this addPrimaryWeaponItem "rhsusf_acc_ACOG_USMC";
_this addPrimaryWeaponItem "rhsusf_acc_grip3";
_this addWeapon "hgun_ACPC2_F";
_this addWeapon "lerca_1200_black";
 
comment "Add items";
_this linkItem "ItemMap";
_this linkItem "ItemCompass";
_this linkItem "tf_microdagr";
_this linkItem "tf_anprc152_4";
_this linkItem "ItemcTab";