comment "Exported from Arsenal by CW2 N. Heintz";

comment "Remove existing items";
removeAllWeapons _this;
removeAllItems _this;
removeAllAssignedItems _this;
removeUniform _this;
removeVest _this;
removeBackpack _this;
removeHeadgear _this;
removeGoggles _this;

comment "Add containers";
_this forceAddUniform "rhs_uniform_FROG01_wd";
_this addVest "rhsusf_spc_squadleader";
for "_i" from 1 to 3 do {_this addItemToVest "ACE_CableTie";};
_this addItemToVest "ACE_EarPlugs";
for "_i" from 1 to 3 do {_this addItemToVest "ACE_morphine";};
for "_i" from 1 to 10 do {_this addItemToVest "ACE_packingBandage";};
for "_i" from 1 to 5 do {_this addItemToVest "adv_aceSplint_splint";};
for "_i" from 1 to 2 do {_this addItemToVest "9Rnd_45ACP_Mag";};
_this addItemToVest "rhs_mag_m67";
for "_i" from 1 to 2 do {_this addItemToVest "ACE_HuntIR_M203";};
for "_i" from 1 to 6 do {_this addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag";};
for "_i" from 1 to 4 do {_this addItemToVest "1Rnd_HE_Grenade_shell";};
_this addBackpack "tfw_ilbe_coy";
for "_i" from 1 to 5 do {_this addItemToBackpack "adv_aceSplint_splint";};
_this addItemToBackpack "rhsusf_ANPVS_14";
_this addItemToBackpack "ItemcTabHCam";
for "_i" from 1 to 5 do {_this addItemToBackpack "ACE_CableTie";};
for "_i" from 1 to 2 do {_this addItemToBackpack "ACE_EarPlugs";};
_this addItemToBackpack "ACE_DefusalKit";
_this addItemToBackpack "ACE_EntrenchingTool";
for "_i" from 1 to 2 do {_this addItemToBackpack "ACE_epinephrine";};
_this addItemToBackpack "ACE_HuntIR_monitor";
_this addItemToBackpack "ACE_IR_Strobe_Item";
_this addItemToBackpack "ACE_Clacker";
for "_i" from 1 to 5 do {_this addItemToBackpack "ACE_morphine";};
_this addItemToBackpack "ACE_surgicalKit";
for "_i" from 1 to 10 do {_this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 5 do {_this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 10 do {_this addItemToBackpack "ACE_elasticBandage";};
for "_i" from 1 to 10 do {_this addItemToBackpack "ACE_quikclot";};
for "_i" from 1 to 2 do {_this addItemToBackpack "rhs_mag_m18_green";};
for "_i" from 1 to 2 do {_this addItemToBackpack "rhs_mag_m18_purple";};
for "_i" from 1 to 2 do {_this addItemToBackpack "rhs_mag_m18_red";};
for "_i" from 1 to 2 do {_this addItemToBackpack "SmokeShellGreen";};
for "_i" from 1 to 2 do {_this addItemToBackpack "SmokeShellRed";};
_this addItemToBackpack "rhs_mag_an_m8hc";
_this addHeadgear "rhsusf_mich_helmet_marpatwd_alt_headset";
_this addGoggles "rhs_googles_clear";

comment "Add weapons";
_this addWeapon "rhs_weap_m4_m320";
_this addPrimaryWeaponItem "rhsusf_acc_SF3P556";
_this addPrimaryWeaponItem "rhsusf_acc_anpeq15_light";
_this addPrimaryWeaponItem "rhsusf_acc_ACOG_3d";
_this addWeapon "hgun_ACPC2_F";
_this addWeapon "lerca_1200_black";

comment "Add items";
_this linkItem "ItemMap";
_this linkItem "ItemCompass";
_this linkItem "tf_microdagr";
_this linkItem "tf_anprc152_14";
_this linkItem "ItemcTab";