comment "Remove existing items";
removeAllWeapons _this;
removeAllItems _this;
removeAllAssignedItems _this;
removeUniform _this;
removeVest _this;
removeBackpack _this;
removeHeadgear _this;
removeGoggles _this;

comment "Add containers";
_this forceAddUniform "VTN_U_FROG_WDL";
_this addVest "rhsusf_spc_rifleman";
for "_i" from 1 to 2 do {_this addItemToVest "rhs_mag_an_m8hc";};
_this addItemToVest "Chemlight_blue";
_this addItemToVest "Chemlight_green";
for "_i" from 1 to 6 do {_this addItemToVest "rhs_mag_30Rnd_556x45_M855_Stanag";};
_this addBackpack "VTN_ILBE";
_this addItemToBackpack "rhs_8point_marpatd";
for "_i" from 1 to 5 do {_this addItemToBackpack "ACE_elasticBandage";};
for "_i" from 1 to 5 do {_this addItemToBackpack "ACE_quikclot";};
for "_i" from 1 to 5 do {_this addItemToBackpack "ACE_packingBandage";};
for "_i" from 1 to 3 do {_this addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 3 do {_this addItemToBackpack "ACE_CableTie";};
_this addItemToBackpack "ACE_salineIV_250";
_this addItemToBackpack "ACE_EarPlugs";
_this addItemToBackpack "ACE_EntrenchingTool";
_this addItemToBackpack "ACE_SpraypaintBlack";
_this addItemToBackpack "ACE_SpraypaintBlue";
_this addItemToBackpack "ACE_SpraypaintRed";
_this addItemToBackpack "ACE_Flashlight_XL50";
for "_i" from 1 to 2 do {_this addItemToBackpack "rhs_mag_an_m8hc";};
_this addItemToBackpack "SmokeShellBlue";
_this addItemToBackpack "SmokeShellGreen";
for "_i" from 1 to 2 do {_this addItemToBackpack "SmokeShellRed";};
_this addItemToBackpack "Chemlight_red";
for "_i" from 1 to 3 do {_this addItemToBackpack "rhs_mag_m67";};
for "_i" from 1 to 3 do {_this addItemToBackpack "ACE_M84";};
for "_i" from 1 to 4 do {_this addItemToBackpack "rhs_mag_30Rnd_556x45_M855_Stanag";};
_this addHeadgear "rhsusf_lwh_helmet_marpatwd";
_this addGoggles "rhs_googles_clear";

comment "Add weapons";
_this addWeapon "rhs_weap_m16a4_carryhandle";
_this addPrimaryWeaponItem "rhsusf_acc_SFMB556";
_this addPrimaryWeaponItem "rhsusf_acc_anpeq15A";
_this addPrimaryWeaponItem "rhsusf_acc_ACOG_USMC";
_this addWeapon "ACE_VectorDay";

comment "Add items";
_this linkItem "ItemMap";
_this linkItem "ItemCompass";
_this linkItem "ItemWatch";
_this linkItem "tf_anprc152_10";
_this linkItem "ItemGPS";
_this linkItem "rhsusf_ANPVS_15";