comment "Exported from Arsenal by CW2 N. Heintz";

comment "Remove existing items";
removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;

comment "Add containers";
this forceAddUniform "VTN_U_FROG_WDL";
this addVest "rhsusf_spc_teamleader";
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m714_White";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m713_Red";};
for "_i" from 1 to 2 do {this addItemToVest "rhs_mag_m715_Green";};
for "_i" from 1 to 6 do {this addItemToVest "rhs_mag_30Rnd_556x45_M855_Stanag";};
for "_i" from 1 to 6 do {this addItemToVest "rhs_mag_M441_HE";};
this addBackpack "VTN_ILBE";
for "_i" from 1 to 3 do {this addItemToBackpack "ACE_tourniquet";};
this addItemToBackpack "ACE_salineIV_250";
this addItemToBackpack "ACE_SpraypaintRed";
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_packingBandage";};
this addItemToBackpack "ACE_MapTools";
this addItemToBackpack "ACE_Flashlight_XL50";
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_elasticBandage";};
for "_i" from 1 to 5 do {this addItemToBackpack "ACE_quikclot";};
this addItemToBackpack "ACE_SpraypaintBlack";
this addItemToBackpack "ACE_SpraypaintBlue";
for "_i" from 1 to 3 do {this addItemToBackpack "ACE_CableTie";};
this addItemToBackpack "ACE_EarPlugs";
this addItemToBackpack "ACE_EntrenchingTool";
this addItemToBackpack "ACE_HuntIR_monitor";
for "_i" from 1 to 2 do {this addItemToBackpack "SmokeShellRed";};
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_mag_m67";};
for "_i" from 1 to 2 do {this addItemToBackpack "ACE_M84";};
this addItemToBackpack "Chemlight_blue";
this addItemToBackpack "Chemlight_green";
this addItemToBackpack "ACE_Chemlight_HiRed";
for "_i" from 1 to 2 do {this addItemToBackpack "rhs_200rnd_556x45_M_SAW";};
this addItemToBackpack "SmokeShellGreen";
this addItemToBackpack "SmokeShellOrange";
for "_i" from 1 to 4 do {this addItemToBackpack "rhs_mag_an_m8hc";};
for "_i" from 1 to 4 do {this addItemToBackpack "rhs_mag_30Rnd_556x45_M855_Stanag";};
this addHeadgear "rhsusf_lwh_helmet_marpatwd";
this addGoggles "rhs_googles_clear";

comment "Add weapons";
this addWeapon "rhs_weap_m16a4_carryhandle_M203";
this addPrimaryWeaponItem "rhsusf_acc_SF3P556";
this addPrimaryWeaponItem "rhsusf_acc_ACOG_USMC_3d";
this addWeapon "Binocular";

comment "Add items";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "tf_anprc152_3";
this linkItem "ItemGPS";
this linkItem "rhsusf_ANPVS_15";